#!/usr/bin/bash
# 
# This bash script should read the file and create user for each team also print all information about team and user into info.txt file === 
echo "[" > team.json

while IFS="," read -r id name email
do
  echo $id $name
  id=${id}
  icpc_id=${id}
  group_ids=[0]
  name=${name}
  #TODO
  organization_id=${id}

  json_object=$(cat <<EOF
  {
    "id": "$id",
    "icpc_id": "$icpc_id",
    "lable": "$id",
    "group_ids": $group_ids,
    "name": "$name",
    "display_name": "$name"   
  },
EOF
)
echo "$json_object" >> team.json
echo "JSON object written to team.json"
done < <(tail -n +2 $1)

echo "]" >> team.json
