#!/usr/bin/env bash
set -e 

silent() {
  "$@" &>/dev/null
}

renameScript() {
  prefixF="$1"
  for file in *; do
    [ -f "$file" ] || continue 
    base="${file%.*}"           # File name without extension
    ext="${file##*.}"           # Extract extension
    if [ "$file" = "$ext" ]; then
     silent mv "$file" "${file}.${prefixF}"
    else
     silent mv "$file" "${base}.${prefixF}"
    fi
  done
}

echo "This script run in $(pwd)"
read -p "this is ok? y/N " letsgo
if [ $letsgo = "y" ];then
  echo ""
  echo "Lets go"
  echo ""
else 
  exit 1
fi

problems=$(find ./ -maxdepth 1 -mindepth 1 -type d | awk -F'./' '{print $2}') 

for item in $problems; do
  echo $item
  silent pushd $item 

  silent ls Data 
  if [[ $? -eq 0 ]];then
  silent mv Data data 
  fi

  mkdir data/secret data/sample
  # go to data/in and rename that then move the files 
  silent pushd data/in 
  renameScript in
  silent mv *sample* ../sample/
  silent mv * ../secret/
  silent popd
  # go to data/out and rename that then move the files 
  silent pushd data/out
  renameScript ans 
  silent mv *sample* ../sample/
  silent mv * ../secret/
  silent popd
  # remove the useless directory
  rm -r data/in data/out
  silent zip -r ${item}.zip ./*
  silent mv ${item}.zip ../
  echo "Finish the $item"
  silent popd
done 
