#!/usr/bin/bash
# This bash script should read the file and create user for each team also print all information about team and user into info.txt file === 

echo "[" > team.json

while IFS="," read -r id name email
do
  newId=$((id + 2))
  #echo $newId
  echo $id $name
  id=$newId
  icpc_id=$newId
  group_ids=[3]
  name=${name}
  # If you need affiliation
  organization_id=$newId

  json_object=$(cat <<EOF
  {
    "id": "$id",
    "icpc_id": "$icpc_id",
    "group_ids": $group_ids,
    "name": "$name",
    "display_name": "$name"   
  },
EOF
)
echo "$json_object" >> team.json
echo "JSON team.json $json_object"
done < <(cat $1)

echo "]" >> team.json
