#!/usr/bin/bash
# this file generate acc for each team base on json file

outputFile=$1
> $outputFile

create_account() {
    local random_number=$((RANDOM % 10000))
    echo "t${id:0:3}${name:0:3}${random_number}" 

    local email=$6
    local id="$1"
    local username=${email%@*}
    #local username="t${id:0:3}${2:0:3}${random_number}"
    # local password=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 4)
    local password=$email
    local type="$3"
    local name="$4"
    local team_id="$5"

    echo "- id: team${id}" >> $outputFile
    # this fix the id 
    echo "  username: $username" >> $outputFile
    echo "  team_id: $((team_id - 32))" >> $outputFile
    echo "  type: $type" >> $outputFile
    echo "  name: $name" >> $outputFile
    echo "  password: $password" >> $outputFile
    echo "" >> $outputFile
}


while  read -r obj; do
 name=$(echo "$obj" | jq -r '.name')
 id=$(echo "$obj" | jq -r '.id')
 email=$(echo "$obj" | jq -r '.email')
 create_account ${id} "$name" "team" "${name}" "${id}" "$email"

done < <(jq -c '.[]' team.json) 
